apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
  - name: config-pod
    image: nginx
    env:
    - name: COURSE
      valueFrom:
        configMapKeyRef: #instead of storing and hardcoding values of environment vraiables we will get them from configmap
          name: course-config
          key: COURSE
    - name: PERSON
      valueFrom:
        configMapKeyRef:
          name: course-config
          key: STUDENT
    - name: YEAR
      valueFrom:
        configMapKeyRef:
          name: course-config
          key: YEAR